site_name: Reqtrace
nav:
  - Home: index.md
  - Concept: concept.md
  - Syntax: syntax.md
  - Workflow: workflow.md
  - Rules: rules.md
  - Edge Cases: edge-cases.md
  - Example Requirement: requirements.md
